In [ ]:
import numpy as np

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a[2]

33

In [ ]:
a[0:4]

array([11, 22, 33, 44])

In [ ]:
a[0:4:2]

array([11, 33])

In [ ]:
a[[7, 0, 3, 3, 3, 0, 7]]

array([88, 11, 44, 44, 44, 11, 88])

In [ ]:
a[a > 50]

array([55, 66, 77, 88, 99])

In [ ]:
a[(a > 50) & ( a < 70)]

array([55, 66])

In [ ]:
a > 50

array([False, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(4, 2)

ValueError: ignored

In [ ]:
a.reshape(-1, 4, 1).shape

(3, 4, 1)

In [ ]:
a[2][1]

9

In [ ]:
a[2, 1]

9

In [ ]:
a = np.random.randint(0, 15, size=(4, 6))
a

array([[10, 12, 13, 14,  2,  4],
       [ 7,  7,  9,  1,  7, 14],
       [ 0,  6, 13,  9,  9,  7],
       [13,  6,  9,  1,  0, 12]])

In [ ]:
np.random.seed(1)

In [ ]:
a = np.random.randint(0, 15, size=(4, 6, 3))
a

array([[[ 1,  8,  8],
        [13,  3, 10],
        [ 9,  8, 14],
        [ 7,  3,  6],
        [ 5,  1,  9],
        [ 3,  4,  8]],

       [[ 1, 11, 12],
        [10,  4,  0],
        [13,  3,  9],
        [ 2,  0,  4],
        [ 9,  2,  7],
        [ 7, 10,  9]],

       [[ 8,  6,  9],
        [ 3,  7, 14],
        [ 7, 13,  4],
        [11,  5,  9],
        [ 3,  6,  8],
        [ 0,  2, 10]],

       [[ 7,  7,  9],
        [ 7,  3, 12],
        [10, 14, 14],
        [ 0,  8,  7],
        [ 7,  1,  1],
        [13,  3,  0]]])

In [ ]:
a.min()

0

In [ ]:
a.min(axis=0)    #  минимальные элементы по столбцам

array([[1, 6, 8],
       [3, 3, 0],
       [7, 3, 4],
       [0, 0, 4],
       [3, 1, 1],
       [0, 2, 0]])

In [ ]:
a.min(axis=2)    #  минимальные элементы по строкам

array([[ 1,  3,  8,  3,  1,  3],
       [ 1,  0,  3,  0,  2,  7],
       [ 6,  3,  4,  5,  3,  0],
       [ 7,  3, 10,  0,  1,  0]])

In [ ]:
a.sum()    #  среднее по столбцам

481

In [ ]:
np.std(a, axis=1)    #  стандартное отклонение по строкам

array([[3.94405319, 2.62995564, 2.47767812],
       [4.28174419, 4.0824829 , 3.89087251],
       [3.68178701, 3.30403793, 2.94392029],
       [3.94405319, 4.3204938 , 5.20949987]])

In [ ]:
np.log1p(a)

array([[[0.69314718, 2.19722458, 2.19722458],
        [2.63905733, 1.38629436, 2.39789527],
        [2.30258509, 2.19722458, 2.7080502 ],
        [2.07944154, 1.38629436, 1.94591015],
        [1.79175947, 0.69314718, 2.30258509],
        [1.38629436, 1.60943791, 2.19722458]],

       [[0.69314718, 2.48490665, 2.56494936],
        [2.39789527, 1.60943791, 0.        ],
        [2.63905733, 1.38629436, 2.30258509],
        [1.09861229, 0.        , 1.60943791],
        [2.30258509, 1.09861229, 2.07944154],
        [2.07944154, 2.39789527, 2.30258509]],

       [[2.19722458, 1.94591015, 2.30258509],
        [1.38629436, 2.07944154, 2.7080502 ],
        [2.07944154, 2.63905733, 1.60943791],
        [2.48490665, 1.79175947, 2.30258509],
        [1.38629436, 1.94591015, 2.19722458],
        [0.        , 1.09861229, 2.39789527]],

       [[2.07944154, 2.07944154, 2.30258509],
        [2.07944154, 1.38629436, 2.56494936],
        [2.39789527, 2.7080502 , 2.7080502 ],
        [0.        , 2.19722

In [ ]:
?np.log*

In [ ]:
a = np.arange(48).reshape(4, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(4, 3, 4)

In [ ]:
a.size

48

In [ ]:
a.itemsize    #  эквивалентно ndarray.dtype.itemsize

8

In [ ]:
a.size * a.itemsize

384

In [ ]:
b = [1] * 48

In [ ]:
import sys 
sys.getsizeof(b)

456

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a.shape

(4, 3, 4)

In [ ]:
c = np.zeros_like(a)
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
c.shape

(4, 3, 4)

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3,3), dtype=complex)  #  Можно изменить тип массива

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [ ]:
np.ones((3,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.empty([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a.shape

(4, 3, 4)

In [ ]:
print(a.ravel()) # стягивание в одномерный массив

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Генерация массивов***

In [ ]:
np.arange(10)    #  От 0 до указанного числа

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 20)    #  Диапазон

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20, 100, 10)    #  Диапазон с заданным шагом

array([20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(0, 1, 0.1)    #  Аргументы могут иметь тип float

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

***Инициализация многомерных массивов***

In [ ]:
b = np.arange(16).reshape(4, 4)    #  Двумерный массив
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
c = np.arange(30).reshape(5, 2, 3)    #  Трехмерный массив
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


***Могут понадобиться константы***

In [ ]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [ ]:
print(b)
print(b.cumsum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]


***Посмотрим на сортировку numpy-массивов.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Теперь попробуем как метод.***

In [ ]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

***Объединим массивы.***

In [ ]:
c = np.hstack((a, b, 5*b))
c

array([-2.,  0.,  1.,  5.,  6., 10., 18.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

***Расщепление массива.***

In [ ]:
a

array([-2,  0,  1,  5,  6, 10, 18])

In [ ]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1]
[5 6]
[10]
[18]


***Функции ``append`` ``delete`` ``insert`` не Inplace функции.***

In [ ]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-2  5 10 18]
[-2  0  1  5  6 10 18]


In [ ]:
np.insert(a, 2, [-1, -1])

array([-2,  0, -1, -1,  1,  5,  6, 10, 18])

In [ ]:
np.append(a, [2.2, 2.1])

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 18. ,  2.2,  2.1])

***Умножение матриц.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [ ]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


***Маски.***

In [ ]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


***След (trace) - сумма диагональных элементов.***

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145
