In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [ ]:
print(tf.executing_eagerly()) # режим активного выполнения

True


In [ ]:
a = tf.constant([[1,2],[3,4]])
print(a)
b = tf.constant([1, 2, 3, 4])
print(b)
c = tf.constant([[1,2],
                 [3,4],
                 [5,6]], dtype=tf.float16)
print(c)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
c = tf.constant([[1,2],
                 [3,4 ,5],
                 [5,6]], dtype=tf.float16)
print(c) # Только прямоугольные матрицы

ValueError: ignored

In [ ]:
с2 = tf.cast(c, dtype=tf.float32)
print(с2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [ ]:
v1 = tf.Variable(-1)
v2 = tf.Variable(b)
print(v1)
print(v2)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=-1>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [ ]:
v1.assign(0)
print(v1)
v2.assign([0, 1, 7, 8])
print(v2)
v2.assign([0, 1, 7]) # Raise Exception

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 7, 8], dtype=int32)>


ValueError: ignored

In [ ]:
v2.assign_add([1, 1, 1, 1]) # Добавление значений
v1.assign_sub(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=-10>

In [ ]:
val_0 = v2[0]
print(val_0)
val_12 = v2[1:3]
print(val_12)
val_0.assign(10)
print(val_0)
print(v2)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 9], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  3,  9, 10], dtype=int32)>


In [ ]:
a = tf.constant([[1,2],[3,4]])
print(a)
a = tf.random.normal(shape=(10,3), dtype=tf.float64)
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1.42990034 -0.85242201 -0.17607377]
 [-0.43083898 -0.56763698  0.10498785]
 [ 1.0055119  -0.51386224  1.65042604]
 [-0.07642433  0.94617314 -0.85343946]
 [-0.36974769 -1.09051717 -0.2154226 ]
 [-1.57370513  1.74964359  1.74689659]
 [ 1.23304884  0.25744586 -2.0021853 ]
 [-0.74895998  0.25355869 -1.78984496]
 [ 0.72332367  0.7801889   1.18340416]
 [ 1.39451151 -0.30267391 -1.73879514]], shape=(10, 3), dtype=float64)


In [ ]:
x =tf.constant(range(10)) + 5
x_indx = tf.gather(x, [0, 4])
print(x, x_indx, sep='\n')

tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)


In [ ]:
v2 = tf.constant([[1,2,7], [3,4,5], [5,6,7]])
val_indx = v2[1,2]
print(val_indx)
print(v2[1:, 1]) # start:stop:step

In [ ]:
a = tf.constant(range(30))
b = tf.reshape(a, [5,6])
print(b.numpy())
print(tf.reshape(a, [-1, 6]).numpy())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
print(tf.zeros((3,3)))
print(tf.zeros_like(b))
print(tf.eye(3, 3))
print(tf.fill((3,3), 3))
print(tf.ones((3,3)))
print(tf.ones_like(b))
print(tf.identity(b))

In [ ]:
x = tf.Variable(-1.0)
y = lambda : x ** 2  - x
N = 100
opt = tf.optimizers.SGD(learning_rate=0.1)
for n in range(N):
  opt.minimize(y, [x])

print(x.numpy())

0.49999994


In [ ]:
print(tf.random.normal((2,4), 0 , 0.1))
print(tf.random.uniform((2,2), -1, 1))
print(tf.random.truncated_normal((1,5), 0, 1))

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([9, 8 , 7])
print(tf.add(a, b))
print(a + b)
print(tf.subtract(a, b))
print(a - b)
print(tf.divide(a, b))
print( a / b)
print(tf.multiply(a, b))
print(a * b)
print(a // b)
print(a ** 2)
print(tf.tensordot(a, b, axes=0))
print(tf.tensordot(b, a, axes=0))

print(tf.tensordot(a, b, axes=1))
print(tf.matmul(tf.tensordot(a, b, axes=0), tf.tensordot(b, a, axes=0)))

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9 18 27]
 [ 8 16 24]
 [ 7 14 21]], shape=(3, 3), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[ 194  388  582]
 [ 388  776 1164]
 [ 582 1164 1746]], shape=(3, 3), dtype=int32)


In [ ]:
tf.reduce_sum(b,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
tf.sin(tf.Variable(3.14))

<tf.Tensor: shape=(), dtype=float32, numpy=0.001592548>

In [ ]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
  tape.watch(a)  # Start recording the history of operations applied to `a`
  tape.watch(b)
  c = tf.sqrt(tf.square(a) + tf.square(b))  # Do some math using `a`
  # What's the gradient of `c` with respect to `a`?
  dc_db = tape.gradient(c, b)
  print(dc_db)

tf.Tensor(
[[-0.5887585  -0.86679506]
 [ 0.1370973  -0.6154888 ]], shape=(2, 2), dtype=float32)


In [ ]:
# Linear Regression

In [ ]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification, make_regression
from sklearn.model_selection import train_test_split
import random

In [ ]:
np.random.seed(13) # pick the seed for reproducability - change it to explore the effects of random variations

train_x = np.linspace(0, 3, 120)
train_labels = 2 * train_x + 0.9 + np.random.randn(*train_x.shape) * 0.5 # 2x + 0.9 + Noise

plt.scatter(train_x,train_labels)


In [ ]:
input_dim = 1
output_dim = 1
learning_rate = 0.1

# This is our weight matrix
w = tf.Variable([[100.0]])
# This is our bias vector
b = tf.Variable(tf.zeros(shape=(output_dim,)))

def f(x):
  return tf.matmul(x,w) + b

def compute_loss(labels, predictions):
  return tf.reduce_mean(tf.square(labels - predictions))

In [ ]:
def train_on_batch(x, y):
  with tf.GradientTape() as tape:
    predictions = f(x)
    loss = compute_loss(y, predictions)
    # Note that `tape.gradient` works with a list as well (w, b).
    dloss_dw, dloss_db = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * dloss_dw)
  b.assign_sub(learning_rate * dloss_db)
  return loss

In [ ]:
# Shuffle the data.
indices = np.random.permutation(len(train_x))
features = tf.constant(train_x[indices],dtype=tf.float32)
labels = tf.constant(train_labels[indices],dtype=tf.float32)

In [ ]:
%time
batch_size = 4
for epoch in range(10):
  for i in range(0,len(features),batch_size):
    loss = train_on_batch(tf.reshape(features[i:i+batch_size],(-1,1)),tf.reshape(labels[i:i+batch_size],(-1,1)))
  print('Epoch %d: last batch loss = %.4f' % (epoch, float(loss)))

In [ ]:
w,b

In [ ]:
plt.scatter(train_x,train_labels)
x = np.array([min(train_x),max(train_x)])
y = w.numpy()[0,0]*x+b.numpy()[0]
plt.plot(x,y,color='red')

In [ ]:
@tf.function
def train_on_batch(x, y):
  with tf.GradientTape() as tape:
    predictions = f(x)
    loss = compute_loss(y, predictions)
    # Note that `tape.gradient` works with a list as well (w, b).
    dloss_dw, dloss_db = tape.gradient(loss, [w, b])
  w.assign_sub(learning_rate * dloss_dw)
  b.assign_sub(learning_rate * dloss_db)
  return loss

In [ ]:
w.assign([[10.0]])
b.assign([0.0])

# Create a tf.data.Dataset object for easy batched iteration
dataset = tf.data.Dataset.from_tensor_slices((train_x.astype(np.float32), train_labels.astype(np.float32)))
dataset = dataset.shuffle(buffer_size=1024).batch(256)

for epoch in range(10):
  for step, (x, y) in enumerate(dataset):
    loss = train_on_batch(tf.reshape(x,(-1,1)), tf.reshape(y,(-1,1)))
  print('Epoch %d: last batch loss = %.4f' % (epoch, float(loss)))

In [ ]:
# Classification

In [ ]:
np.random.seed(0) # pick the seed for reproducibility - change it to explore the effects of random variations

n = 100
X, Y = make_classification(n_samples = n, n_features=2,
                           n_redundant=0, n_informative=2, flip_y=0.05,class_sep=1.5)
X = X.astype(np.float32)
Y = Y.astype(np.int32)

split = [ 70*n//100, (15+70)*n//100 ]
train_x, valid_x, test_x = np.split(X, split)
train_labels, valid_labels, test_labels = np.split(Y, split)

In [ ]:
def plot_dataset(features, labels, W=None, b=None):
    # prepare the plot
    fig, ax = plt.subplots(1, 1)
    ax.set_xlabel('$x_i[0]$ -- (feature 1)')
    ax.set_ylabel('$x_i[1]$ -- (feature 2)')
    colors = ['r' if l else 'b' for l in labels]
    ax.scatter(features[:, 0], features[:, 1], marker='o', c=colors, s=100, alpha = 0.5)
    if W is not None:
        min_x = min(features[:,0])
        max_x = max(features[:,1])
        min_y = min(features[:,1])*(1-.1)
        max_y = max(features[:,1])*(1+.1)
        cx = np.array([min_x,max_x],dtype=np.float32)
        cy = (0.5-W[0]*cx-b)/W[1]
        ax.plot(cx,cy,'g')
        ax.set_ylim(min_y,max_y)
    fig.show()

In [ ]:
plot_dataset(train_x, train_labels)

In [ ]:
train_x_norm = (train_x-np.min(train_x)) / (np.max(train_x)-np.min(train_x))
valid_x_norm = (valid_x-np.min(train_x)) / (np.max(train_x)-np.min(train_x))
test_x_norm = (test_x-np.min(train_x)) / (np.max(train_x)-np.min(train_x))

In [ ]:
W = tf.Variable(tf.random.normal(shape=(2,1)),dtype=tf.float32)
b = tf.Variable(tf.zeros(shape=(1,),dtype=tf.float32))

learning_rate = 0.1

@tf.function
def train_on_batch(x, y):
  with tf.GradientTape() as tape:
    z = tf.matmul(x, W) + b
    loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y,logits=z))
  dloss_dw, dloss_db = tape.gradient(loss, [W, b])
  W.assign_sub(learning_rate * dloss_dw)
  b.assign_sub(learning_rate * dloss_db)
  return loss

In [ ]:
# Create a tf.data.Dataset object for easy batched iteration
dataset = tf.data.Dataset.from_tensor_slices((train_x_norm.astype(np.float32), train_labels.astype(np.float32)))
dataset = dataset.shuffle(128).batch(2)

for epoch in range(10):
  for step, (x, y) in enumerate(dataset):
    loss = train_on_batch(x, tf.expand_dims(y,1))
  print('Epoch %d: last batch loss = %.4f' % (epoch, float(loss)))

In [ ]:
plot_dataset(train_x,train_labels,W.numpy(),b.numpy())

In [ ]:
pred = tf.matmul(test_x,W)+b
fig,ax = plt.subplots(1,2)
ax[0].scatter(test_x[:,0],test_x[:,1],c=pred[:,0]>0.5)
ax[1].scatter(test_x[:,0],test_x[:,1],c=valid_labels)

In [ ]:
tf.reduce_mean(tf.cast(((pred[0]>0.5)==test_labels),tf.float32))

In [ ]:
optimizer = tf.keras.optimizers.Adam(0.01)

W = tf.Variable(tf.random.normal(shape=(2,1)))
b = tf.Variable(tf.zeros(shape=(1,),dtype=tf.float32))

@tf.function
def train_on_batch(x, y):
  vars = [W, b]
  with tf.GradientTape() as tape:
    z = tf.sigmoid(tf.matmul(x, W) + b)
    loss = tf.reduce_mean(tf.keras.losses.binary_crossentropy(z,y))
    correct_prediction = tf.equal(tf.round(y), tf.round(z))
    acc = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    grads = tape.gradient(loss, vars)
    optimizer.apply_gradients(zip(grads,vars))
  return loss,acc

for epoch in range(20):
  for step, (x, y) in enumerate(dataset):
    loss,acc = train_on_batch(tf.reshape(x,(-1,2)), tf.reshape(y,(-1,1)))
  print('Epoch %d: last batch loss = %.4f, acc = %.4f' % (epoch, float(loss),acc))

In [ ]:
inputs = tf.keras.Input(shape=(2,))
z = tf.keras.layers.Dense(1,kernel_initializer='glorot_uniform',activation='sigmoid')(inputs)
model = tf.keras.models.Model(inputs,z)

model.compile(tf.keras.optimizers.Adam(0.1),'binary_crossentropy',['accuracy'])
model.summary()
h = model.fit(train_x_norm,train_labels,batch_size=8,epochs=15)

In [ ]:
plt.plot(h.history['accuracy'])

In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(5,activation='sigmoid',input_shape=(2,)))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

model.compile(tf.keras.optimizers.Adam(0.1),'binary_crossentropy',['accuracy'])
model.summary()
model.fit(train_x_norm,train_labels,validation_data=(test_x_norm,test_labels),batch_size=8,epochs=15)

In [ ]:
class DenseNN(tf.Module):
  def __init__(self, outputs):
    super().__init__()
    self.outputs = outputs
    self.fl_init = False

  def __call__(self, x):
    if not self.fl_init:
      self.w = tf.random.truncated_normal((x.shape[-1], self.outputs), stddev=0.1, name="W")
      self.b = tf.zeros([self.outputs], dtype=tf.float32, name="b")

      self.w = tf.Variable(self.w)
      self.b = tf.Variable(self.b)

      self.fl_init = True
    y = x @ self.w + self.b
    return y

In [ ]:
model = DenseNN(1)
x_train = tf.random.uniform(minval=0, maxval=10, shape=(100, 2))
y_train = [a + b for a, b in x_train]
loss = lambda x, y: tf.reduce_mean(tf.square(x - y))

opt = tf.optimizers.Adam(learning_rate=0.01)


EPOCHS = 50
for n in range(EPOCHS):
  for x, y in zip(x_train, y_train):
    x = tf.expand_dims(x, axis=0)
    y = tf.constant(y, shape=(1, 1))

    with tf.GradientTape() as tape:
      f_loss = loss(y, model(x))

    grads = tape.gradient(f_loss, model.trainable_variables)
    opt.apply_gradients(zip(grads, model.trainable_variables))

  print(f_loss.numpy())

In [ ]:
print(model(tf.constant([[1.0, 2.0]])))
print(model(tf.constant([[5.0, 2.0]])))

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train / 255
x_test = x_test / 255

x_train = tf.reshape(tf.cast(x_train, tf.float32), [-1, 28*28])
x_test = tf.reshape(tf.cast(x_test, tf.float32), [-1, 28*28])

y_train = to_categorical(y_train, 10)

In [ ]:
class DenseNN(tf.Module):
  def __init__(self, outputs, activate="relu"):
    super().__init__()
    self.outputs = outputs
    self.activate = activate
    self.fl_init = False

  def __call__(self, x):
    if not self.fl_init:
      self.w = tf.random.truncated_normal((x.shape[-1], self.outputs), stddev=0.1, name="W")
      self.b = tf.zeros([self.outputs], dtype=tf.float32, name="b")

      self.w = tf.Variable(self.w)
      self.b = tf.Variable(self.b)

      self.fl_init = True
    y = x @ self.w + self.b

    if self.activate == "relu":
      return tf.nn.relu(y)
    elif self.activate == "softmax":
      return tf.nn.softmax(y)

In [ ]:
hidden_layer = DenseNN(128)
output_layer = DenseNN(10, activate="softmax")

def model_predict(x):
  return output_layer(hidden_layer(x))

cross_entropy = lambda y_true, y_pred: tf.reduce_mean(tf.losses.categorical_crossentropy(y_true, y_pred))

opt = tf.optimizers.Adam(learning_rate=0.001)

BATCH_SIZE = 32
EPOCHS = 10
TOTAL = x_train.shape[0]

train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(BATCH_SIZE)


In [ ]:
for n in range(EPOCHS):
  loss = 0
  for x_batch, y_batch in train_dataset:

    with tf.GradientTape() as tape:
      f_loss = cross_entropy(y_batch, model_predict(x_batch))
    loss += f_loss
    grads = tape.gradient(f_loss, [hidden_layer.trainable_variables, output_layer.trainable_variables])
    opt.apply_gradients(zip(grads[1], output_layer.trainable_variables))
    opt.apply_gradients(zip(grads[0], hidden_layer.trainable_variables))

  print(loss.numpy())

In [ ]:
y = model_predict(x_test)

y2 = tf.argmax(y , axis=1).numpy()
acc = len(y_test[y_test == y2])/ y_test.shape[0] * 100
print(acc)

In [ ]:
acc = tf.metrics.Accuracy()
acc.update_state(y_test, y2)
print(acc.result().numpy() * 100)

In [ ]:
y_test_cat = to_categorical(y_test, 10)

In [ ]:
acc = tf.metrics.Recall()
acc.update_state(y_test_cat, y)
print(acc.result().numpy() * 100)

In [ ]:
acc = tf.metrics.Precision()
acc.update_state(y_test_cat, y)
print(acc.result().numpy() * 100)

In [ ]:
class SequentialModule(tf.Module):
  def __init__(self):
    super().__init__()
    self.layer_1 = DenseNN(128)
    self.layer_2 = DenseNN(10, activate="softmax")


  def __call__(self, x):
    return self.layer_2(self.layer_1(x))

In [ ]:
model = SequentialModule()
print(model.submodules)

In [ ]:
@tf.function
def train_batch(x_batch, y_batch):
   with tf.GradientTape() as tape:
      f_loss = cross_entropy(y_batch, model(x_batch))
   grads = tape.gradient(f_loss, model.trainable_variables)
   opt.apply_gradients(zip(grads, model.trainable_variables))
   return f_loss

In [ ]:
for n in range(EPOCHS):
  loss = 0
  for x_batch, y_batch in train_dataset:
    loss += train_batch(x_batch, y_batch)
  print(loss.numpy())

In [ ]:
y = model(x_test)

y2 = tf.argmax(y , axis=1).numpy()
acc = len(y_test[y_test == y2])/ y_test.shape[0] * 100
print(acc)

In [ ]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import os
import glob
from PIL import Image

In [ ]:
def check_image_dir(path):
    for fn in glob.glob(path):
        if not check_image(fn):
            print("Corrupt image or wrong format: {}".format(fn))
            os.remove(fn)


def check_image(fn):
    try:
        im = Image.open(fn)
        im.verify()
        return im.format=='JPEG'
    except:
        return False


def display_dataset(dataset, labels=None, n=10, classes=None):
    fig,ax = plt.subplots(1,n,figsize=(15,3))
    for i in range(n):
        ax[i].imshow(dataset[i])
        ax[i].axis('off')
        if classes is not None and labels is not None:
            ax[i].set_title(classes[labels[i][0]])

In [ ]:
if not os.path.exists('data/kagglecatsanddogs_5340.zip'):
    !wget -P data https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip

In [ ]:
import zipfile
if not os.path.exists('data/PetImages'):
    with zipfile.ZipFile('data/kagglecatsanddogs_5340.zip', 'r') as zip_ref:
        zip_ref.extractall('data')

In [ ]:
check_image_dir('data/PetImages/Cat/*.jpg')
check_image_dir('data/PetImages/Dog/*.jpg')

In [ ]:
data_dir = 'data/PetImages'
batch_size = 64
ds_train = keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split = 0.2,
    subset = 'training',
    seed = 13,
    image_size = (224,224),
    batch_size = batch_size
)
ds_test = keras.preprocessing.image_dataset_from_directory(
    data_dir,
    validation_split = 0.2,
    subset = 'validation',
    seed = 13,
    image_size = (224,224),
    batch_size = batch_size
)

In [ ]:
for x,y in ds_train:
    print(f"Training batch shape: features={x.shape}, labels={y.shape}")
    x_sample, y_sample = x,y
    break
    
display_dataset(x_sample.numpy().astype(np.int),np.expand_dims(y_sample,1),classes=ds_train.class_names)

In [ ]:
vgg = keras.applications.VGG16()
inp = keras.applications.vgg16.preprocess_input(x_sample[:1])

res = vgg(inp)
print(f"Most probable class = {tf.argmax(res,1)}")

keras.applications.vgg16.decode_predictions(res.numpy())

In [ ]:
vgg.summary()

In [ ]:
tf.config.list_physical_devices('GPU')

In [ ]:
vgg = keras.applications.VGG16(include_top=False)

inp = keras.applications.vgg16.preprocess_input(x_sample[:1])
res = vgg(inp)
print(f"Shape after applying VGG-16: {res[0].shape}")
plt.figure(figsize=(15,3))
plt.imshow(res[0].numpy().reshape(-1,512))

In [ ]:
num = batch_size*50
ds_features_train = ds_train.take(50).map(lambda x,y : (vgg(x),y))
ds_features_test = ds_test.take(10).map(lambda x,y : (vgg(x),y))

for x,y in ds_features_train:
    print(x.shape,y.shape)
    break

In [ ]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(7,7,512)),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
hist = model.fit(ds_features_train, validation_data=ds_features_test)

In [ ]:
# Encoder - Decoder